# Numpy Array

In [2]:
# Array and Matrix Manipulation we are going to use Numpy 
import numpy as np
a = np.array(["vbhvh", 2, 3]) # coverting list  into array
a.shape

(3,)

In [2]:
#Upcasting:

In [3]:
np.array([1, 2, 3.0])

array([1., 2., 3.])

In [4]:
#two dimensions

In [3]:
a = np.array([[1, 2], [3, 4]]) # list with in list numpy create 2 dimensional Array
a.shape

(2, 2)

In [6]:
#Minimum dimensions 2:

In [4]:
a = np.array([1, 2, 3], ndmin=5) # creating 5 dimension array
a.shape

(1, 1, 1, 1, 3)

In [8]:
#dtype

In [5]:
 np.array([1, 2, 3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [12]:
#Data-type consisting of more than one element:

In [6]:
x = np.array([(1,2),(3,4)],dtype=[('a','<i2'),('b','<i8')])
x

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [7]:
type(x[1][0])

numpy.int16

In [8]:
#Creating an array from sub-classes:

In [9]:
np.mat(np.array([[1, 2],[4,7]]))

matrix([[1, 2],
        [4, 7]])

In [10]:
np.mat('1 2; 3 4')

matrix([[1, 2],
        [3, 4]])

# numpy.asarray

In [11]:
#Convert the input to an array.

In [12]:
#Convert a list into an array:

In [13]:
 a = [1, 2]
type(a)

list

In [14]:
type(np.asarray(a))

numpy.ndarray

In [15]:
a = np.array([1, 2]) #Existing arrays are not copied
type(a)

numpy.ndarray

In [16]:
np.asarray((1,2))

array([1, 2])

In [17]:
#If dtype is set, array is copied only if dtype does not match:

In [18]:
a = np.array([1, 2], dtype=np.float32)
a

array([1., 2.], dtype=float32)

In [19]:
np.asarray([1,2]) is a

False

In [20]:
np.asarray([1,2])

array([1, 2])

In [21]:
np.asarray(a, dtype=np.float64) is a

False

In [22]:
# ndarray subclasses are not passed through

In [23]:
issubclass(np.matrix, np.ndarray)

True

In [24]:
a = np.matrix([[1, 2]])
np.asanyarray(a)


matrix([[1, 2]])

In [25]:
np.asarray(a) is a

False

In [26]:
np.asanyarray(a) is a

True

In [51]:
type(np.asarray(a))

numpy.ndarray

# numpy.asanyarray

In [27]:
a = [1, 2]
np.asanyarray(a)

array([1, 2])

In [28]:
a = np.matrix([1, 2])
a

matrix([[1, 2]])

In [29]:
np.asanyarray([1,2]) is a

False

In [31]:
np.array(a, copy=True)  

array([[1, 2]])

In [35]:
#Create an array x, with a reference y and a copy z:

In [36]:
x = np.array([1, 2, 3])
x
y

array([1, 2, 3])

In [37]:
y = x

In [40]:
z = np.copy(x) # Reflect/change the  original data both are pointing to same location

In [41]:
y[0] = 100
x

array([100,   2,   3])

In [42]:
x

array([100,   2,   3])

In [43]:
id(x[0])

163222736

In [44]:
id(y[0])

163222896

In [45]:
id(x) 

152247712

In [46]:
id(y)

152247712

# numpy.fromfunction

In [47]:
#Construct an array by executing a function over each coordinate.

In [48]:
np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [50]:
np.fromfunction(lambda i, j: i + j, (3, 3), dtype=int)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [51]:
np.fromfunction(lambda i, j: i * j, (3, 3), dtype=int)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [52]:
#Create a new 1-dimensional array from an iterable object.

In [55]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [56]:
iterable = (x*x for x in range(5))
iterable

<generator object <genexpr> at 0x0000000004F038C8>

In [60]:
np.array(list(range(10)))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
np.asanyarray(list(range(10)))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
np.fromiter(range(10),int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [64]:
#A new 1-D array initialized from text data in a string

In [62]:
a = np.fromstring('234 234',sep=' ')
a

array([234., 234.])

In [63]:
np.fromstring('1, 2', dtype=int, sep=',')

array([1, 2])

In [79]:
# How to create create a record array from a (flat) list of arrays

In [64]:
x1=np.array([1,2,3,4])

In [65]:
x2=np.array(['a','dd','xyz','12'])

In [66]:
x3=np.array([1.1,2,3,4])
x4=np.array([1.1,2,3,4])
type(x4)

numpy.ndarray

In [67]:
r = np.core.records.fromarrays([x1,x2,x3,x4],names='a,b,c,d')
r

rec.array([(1, 'a', 1.1, 1.1), (2, 'dd', 2. , 2. ), (3, 'xyz', 3. , 3. ),
           (4, '12', 4. , 4. )],
          dtype=[('a', '<i4'), ('b', '<U3'), ('c', '<f8'), ('d', '<f8')])

In [68]:
print(r[1]["a"])

2


In [69]:
x1[1]

2

# data types

In [94]:
my_list = [1,2,3]
import numpy as np
arr = np.array(my_list)
print("Type/Class of this object:",type(arr))
print("Here is the vector\n--------------------\n",arr)

Type/Class of this object: <class 'numpy.ndarray'>
Here is the vector
--------------------
 [1 2 3]


In [95]:
arr.dtype

dtype('int32')

In [96]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_mat)
print("Type/Class of this object:",type(mat))
print("Here is the matrix\n----------\n",mat,"\n----------")
print("Dimension of this matrix: ",mat.ndim,sep='') #ndim gives the dimensison, 2 for a matrix, 1 for a vector
print("Size of this matrix: ", mat.size,sep='') #size gives the total number of elements
print("Shape of this matrix: ", mat.shape,sep='') #shape gives the number of elements along each axes (dimension)
print("Data type of this matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array


Type/Class of this object: <class 'numpy.ndarray'>
Here is the matrix
----------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
----------
Dimension of this matrix: 2
Size of this matrix: 9
Shape of this matrix: (3, 3)
Data type of this matrix: int32


In [99]:
my_mat = [[1.1,2,3],[4,5.2,6],[7,8.3,9]]
mat = np.array(my_mat)
print("Data type of the modified matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array
print("\n\nEven tuples can be converted to ndarrays...")
mat.ndim

Data type of the modified matrix: float64


Even tuples can be converted to ndarrays...


2

In [100]:
b = np.array([(1.5,2,3), (4,5,6)])
print("We write b = np.array([(1.5,2,3), (4,5,6)])")
print("Matrix made from tuples, not lists\n---------------------------------------")
print(b)

We write b = np.array([(1.5,2,3), (4,5,6)])
Matrix made from tuples, not lists
---------------------------------------
[[1.5 2.  3. ]
 [4.  5.  6. ]]


# arange and linspace

In [127]:
print("A series of numbers:",type(np.arange(5,16)))
np.arange(5,16,2.3)# A series of numbers from low to high

A series of numbers: <class 'numpy.ndarray'>


array([ 5. ,  7.3,  9.6, 11.9, 14.2])

In [102]:
range(10)

range(0, 10)

In [104]:
np.arange(10.34)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [106]:
np.arange(5.6,10.34,.4)

array([ 5.6,  6. ,  6.4,  6.8,  7.2,  7.6,  8. ,  8.4,  8.8,  9.2,  9.6,
       10. ])

In [107]:
list(range(5,16,2))

[5, 7, 9, 11, 13, 15]

In [108]:
list(range(50,-1,5))

[]

In [109]:
print("Numbers spaced apart by 2:",np.arange(50,-1,5)) # Numbers spaced apart by 2

Numbers spaced apart by 2: []


In [110]:
print("Numbers spaced apart by float:",np.arange(0,11,2.5)) # Numbers spaced apart by 2.5

Numbers spaced apart by float: [ 0.   2.5  5.   7.5 10. ]


In [111]:
print("Every 5th number from 50 in reverse order\n",np.arange(5.0,-1,-5))

Every 5th number from 50 in reverse order
 [5. 0.]


In [112]:
print("21 linearly spaced numbers between 1 and 5\n--------------------------------------------")
print((np.linspace(1,5,50)))

21 linearly spaced numbers between 1 and 5
--------------------------------------------
[1.         1.08163265 1.16326531 1.24489796 1.32653061 1.40816327
 1.48979592 1.57142857 1.65306122 1.73469388 1.81632653 1.89795918
 1.97959184 2.06122449 2.14285714 2.2244898  2.30612245 2.3877551
 2.46938776 2.55102041 2.63265306 2.71428571 2.79591837 2.87755102
 2.95918367 3.04081633 3.12244898 3.20408163 3.28571429 3.36734694
 3.44897959 3.53061224 3.6122449  3.69387755 3.7755102  3.85714286
 3.93877551 4.02040816 4.10204082 4.18367347 4.26530612 4.34693878
 4.42857143 4.51020408 4.59183673 4.67346939 4.75510204 4.83673469
 4.91836735 5.        ]


# Matrix creation

In [114]:
print("Vector of zeroes\n---------------------")
print(np.zeros(5))

Vector of zeroes
---------------------
[0. 0. 0. 0. 0.]


In [115]:
print("Matrix of zeroes\n--------------------")
print(np.zeros((3,4))) # Notice Tuples

Matrix of zeroes
--------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [127]:
print("Vector of ones\n---------------------")
print(np.ones(5))

Vector of ones
---------------------
[1. 1. 1. 1. 1.]


In [116]:
print("Matrix of ones\n---------------------")
print(np.ones((5,2,8))) # Note matrix dimension specified by Tuples


Matrix of ones
---------------------
[[[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]]


In [117]:
print("Matrix of 5's\n---------------------")
print(5+np.ones((3,5)))

Matrix of 5's
---------------------
[[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]


In [119]:
print("Empty matrix\n-------------\n", np.empty((3,5)))

Empty matrix
-------------
 [[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]


In [120]:
mat1 = np.eye(4) 
print("Identity matrix of dimension", mat1.shape)
print(mat1)

Identity matrix of dimension (4, 4)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [121]:
np.arange(3)

array([0, 1, 2])

In [122]:
np.arange(3.0)

array([0., 1., 2.])

In [123]:
 np.arange(3,7)

array([3, 4, 5, 6])

In [124]:
np.arange(3,7,2)

array([3, 5])

In [164]:
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [165]:
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [166]:
np.linspace(2.0, 3.0, num=9, retstep=True)

(array([2.   , 2.125, 2.25 , 2.375, 2.5  , 2.625, 2.75 , 2.875, 3.   ]), 0.125)

In [167]:
#Return numbers spaced evenly on a log scale.
np.linspace(2.0, 3.0, num=4)

array([2.        , 2.33333333, 2.66666667, 3.        ])

In [168]:
np.logspace(2.0, 3.0, num=4,base = 10)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [169]:
np.logspace(2.0, 3.0, num=4, endpoint=False)

array([100.        , 177.827941  , 316.22776602, 562.34132519])

In [170]:
np.logspace(2.0, 3.0, num=4, base=2.0)

array([4.        , 5.0396842 , 6.34960421, 8.        ])

In [171]:
#Extract a diagonal or construct a diagonal array.

In [4]:
import numpy as np
x = np.arange(9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
x.reshape((1,9))

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [6]:
x.reshape((9,1))

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [7]:
x.reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
x.reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
np.diag(x)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8]])

In [11]:
np.diag(x, k=2)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [12]:
np.diag(x, k=-1)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0]])

In [14]:
np.diag(np.diag(x))

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
#Create a two-dimensional array with the flattened input as a diagonal.

In [16]:
np.diagflat([[1,2], [3,4]])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [17]:
np.diagflat([1,2], 1)

array([[0, 1, 0],
       [0, 0, 2],
       [0, 0, 0]])

In [18]:
#An array with ones at and below the given diagonal and zeros elsewhere.

In [20]:
np.tri(3, 5, 0, dtype=int)

array([[1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0]])

In [21]:
np.tri(3, 5,k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.]])

In [128]:
#return a Lower triangle of an array.

In [23]:
np.tril([[1,2,3],[4,5,6],[7,8,9]], 0)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [24]:
#return Upper triangle of an array.

In [25]:
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], 1)

array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0],
       [0, 0, 0]])

# Random number generation

In [26]:
print("Random number generation (from Uniform distribution)")
print(np.random.rand(2,3)) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary 

Random number generation (from Uniform distribution)
[[0.02031482 0.7579964  0.72935937]
 [0.78233913 0.82661413 0.67354171]]


In [30]:
np.random.rand(2,3,5)

array([[[1.91582904e-01, 7.00809327e-01, 8.23555658e-01, 3.61846877e-01,
         7.46616399e-01],
        [7.93710936e-01, 2.18267204e-01, 9.29067949e-01, 4.25694432e-01,
         7.62106407e-01],
        [6.61103079e-04, 5.54272983e-01, 9.61352629e-01, 3.28514859e-01,
         3.05497851e-01]],

       [[8.73863181e-03, 1.98313207e-01, 8.96265978e-01, 3.76236797e-01,
         9.83025296e-01],
        [4.70739113e-01, 1.49758161e-01, 7.56171257e-01, 1.96480554e-01,
         5.92600033e-01],
        [2.64351716e-02, 1.22303376e-01, 2.49547885e-01, 5.24838147e-02,
         3.64304778e-01]]])

In [31]:
print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.randn(4,3))

Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal
[[ 2.27910000e-03 -4.67208728e-01 -5.25305095e-01]
 [-2.59271263e-01  1.07291925e-01 -1.09777319e+00]
 [-7.13047811e-01  2.15623372e-01  3.09558690e+00]
 [ 7.62580862e-01  4.13458802e-01 -1.65010268e-01]]


In [32]:
print("Random integer vector:",np.random.randint(1,10)) #randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix")

Random integer vector: 8

Random integer matrix


In [33]:
print(np.random.randint(1,100,(4,4))) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)
print("\n20 samples drawn from a dice throw:",np.random.randint(1,7,20)) # 20 samples drawn from a dice throw

[[86 11 30 96]
 [17 96 35 25]
 [26 50 31 43]
 [ 2 54  8 42]]

20 samples drawn from a dice throw: [6 2 2 6 1 5 1 5 4 3 4 1 2 1 1 1 3 4 6 4]


In [35]:
print(np.random.randint(1,100,10).reshape(5,2))

[[41 36]
 [30 53]
 [14 53]
 [59 64]
 [78 84]]


# Reshaping

In [36]:
from numpy.random import randint as ri
a = ri(1,100,30)
b = a.reshape(2,3,5)
c = a.reshape(6,-19878)
c

array([[ 6, 70, 62, 98, 48],
       [75, 50, 59, 74,  4],
       [73, 58, 37, 24, 13],
       [18, 15, 14, 28,  2],
       [31, 79, 70, 28, 57],
       [50, 18, 15, 82, 41]])

In [37]:
print ("Shape of a:", a.shape)
print ("Shape of b:", b.shape)
print ("Shape of c:", c.shape)


Shape of a: (30,)
Shape of b: (2, 3, 5)
Shape of c: (6, 5)


In [38]:
print("\na looks like\n",'-'*20,"\n",a,"\n",'-'*20)
print("\nb looks like\n",'-'*20,"\n",b,"\n",'-'*20)
print("\nc looks like\n",'-'*20,"\n",c,"\n",'-'*20)



a looks like
 -------------------- 
 [ 6 70 62 98 48 75 50 59 74  4 73 58 37 24 13 18 15 14 28  2 31 79 70 28
 57 50 18 15 82 41] 
 --------------------

b looks like
 -------------------- 
 [[[ 6 70 62 98 48]
  [75 50 59 74  4]
  [73 58 37 24 13]]

 [[18 15 14 28  2]
  [31 79 70 28 57]
  [50 18 15 82 41]]] 
 --------------------

c looks like
 -------------------- 
 [[ 6 70 62 98 48]
 [75 50 59 74  4]
 [73 58 37 24 13]
 [18 15 14 28  2]
 [31 79 70 28 57]
 [50 18 15 82 41]] 
 --------------------


In [39]:
A = ri(1,100,10) # Vector of random interegrs
print("\nVector of random integers\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A))



Vector of random integers
 -------------------------------------------------- 
 [78 45 99 97 95 88 26 43 48 66]

Here is the sorted vector
 -------------------------------------------------- 
 [26 43 45 48 66 78 88 95 97 99]


In [40]:
M = ri(1,100,25).reshape(5,5) # Matrix of random interegrs
#print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M, kind='mergesort')) # Default axis =1
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M, axis=1, kind='mergesort'))
M


Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[22 36 57 62 93]
 [12 17 40 68 73]
 [14 45 61 81 91]
 [ 3 19 64 75 78]
 [46 48 57 67 70]]


array([[57, 93, 62, 22, 36],
       [73, 17, 68, 40, 12],
       [91, 61, 81, 45, 14],
       [64, 78, 75, 19,  3],
       [70, 48, 57, 46, 67]])

In [41]:
print("Max of a:", M.max())
print("Max of b:", b.max())
b

Max of a: 93
Max of b: 98


array([[[ 6, 70, 62, 98, 48],
        [75, 50, 59, 74,  4],
        [73, 58, 37, 24, 13]],

       [[18, 15, 14, 28,  2],
        [31, 79, 70, 28, 57],
        [50, 18, 15, 82, 41]]])

In [42]:
M

array([[57, 93, 62, 22, 36],
       [73, 17, 68, 40, 12],
       [91, 61, 81, 45, 14],
       [64, 78, 75, 19,  3],
       [70, 48, 57, 46, 67]])

In [44]:
print("Max of a location:", M.argmax(axis= 1 ))
print("Max of b location:", b.argmax())
print("Max of c location:", b.argmax())

Max of a location: [1 0 0 1 0]
Max of b location: 3
Max of c location: 3


# Indexing and slicing

In [46]:
arr = np.arange(0,11)
print("Array:",arr)


Array: [ 0  1  2  3  4  5  6  7  8  9 10]


In [47]:
print("Element at 7th index is:", arr[7])


Element at 7th index is: 7


In [48]:
print("Elements from 3rd to 5th index are:", arr[3:6:2])


Elements from 3rd to 5th index are: [3 5]


In [49]:
print("Elements up to 4th index are:", arr[:4])
arr

Elements up to 4th index are: [0 1 2 3]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
print("Elements from last backwards are:", arr[-1:7:-1])


Elements from last backwards are: [10  9  8]


In [51]:
print("3 Elements from last backwards are:", arr[-1:-6:2])


3 Elements from last backwards are: []


In [52]:
arr = np.arange(0,21,2)
print("New array:",arr)


New array: [ 0  2  4  6  8 10 12 14 16 18 20]


In [53]:
print("Elements at 2nd, 4th, and 9th index are:", arr[[2,4,9]]) # Pass a list as a index to subset

Elements at 2nd, 4th, and 9th index are: [ 4  8 18]


In [55]:
import numpy as np 
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)
mat[1:4,3:5]
mat[0:3,[1,3]]

Matrix of random 2-digit numbers
--------------------------------
 [[88 36 51 34 29]
 [46 98 35 35 58]
 [68 82 20 72 50]]


array([[36, 34],
       [98, 35],
       [82, 72]])

In [56]:
mat[0:3,[1,3]]
mat

array([[88, 36, 51, 34, 29],
       [46, 98, 35, 35, 58],
       [68, 82, 20, 72, 50]])

In [57]:
print("\nDouble bracket indexing\n------------------------")
print("Element in row index 1 and column index 2:", mat[1][1])
mat


Double bracket indexing
------------------------
Element in row index 1 and column index 2: 98


array([[88, 36, 51, 34, 29],
       [46, 98, 35, 35, 58],
       [68, 82, 20, 72, 50]])

In [242]:
print("\nSingle bracket with comma indexing\n----------------------------------")
print("Element in row index 1 and column index 2:", mat[1,2])
print("\nRow or column extract\n----------------------")



Single bracket with comma indexing
----------------------------------
Element in row index 1 and column index 2: 75

Row or column extract
----------------------


In [172]:
print("Entire row at index 2:", mat[2])
print("Entire column at index 3:", mat[:,3])


Entire row at index 2: [22 10 57 59 61]
Entire column at index 3: [92 88 59]


In [7]:
print("\nSubsetting sub-matrices\n--------------------------")
print("Matrix with row indices 1 and 2 and column indices 3 and 4\n", mat[1:3,3:5])



Subsetting sub-matrices
--------------------------
Matrix with row indices 1 and 2 and column indices 3 and 4
 [[14 32]
 [62 27]]


In [156]:
print("Matrix with row indices 0 and 1 and column indices 1 and 3\n", mat[0:2,[1,3]])

Matrix with row indices 0 and 1 and column indices 1 and 3
 [[77 69]
 [64 17]]


# Subseting

In [59]:
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)
mat>50

Matrix of random 2-digit numbers
--------------------------------
 [[94 93 37 23 96]
 [24 66 77 95 28]
 [94 33 63 88 45]]


array([[ True,  True, False, False,  True],
       [False,  True,  True,  True, False],
       [ True, False,  True,  True, False]])

In [60]:
print ("Elements greater than 50\n", mat[mat>50])

Elements greater than 50
 [94 93 96 66 77 95 94 63 88]


# Slicing

In [61]:
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print("Original matrix")
print(mat)


Original matrix
[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [62]:
mat_slice = mat[:2,:2]
print ("\nSliced matrix")
print(mat_slice)
print ("\nChange the sliced matrix")


Sliced matrix
[[11 12]
 [21 22]]

Change the sliced matrix


In [63]:
mat_slice[0,0] = 1000
print (mat_slice)

[[1000   12]
 [  21   22]]


In [64]:
print("\nBut the original matrix? WHOA! It got changed too!")
print(mat)



But the original matrix? WHOA! It got changed too!
[[1000   12   13]
 [  21   22   23]
 [  31   32   33]]


In [65]:
# Little different way to create a copy of the slixed matrix
print ("\nDoing it again little differently now...\n")
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print("Original matrix")
print(mat)



Doing it again little differently now...

Original matrix
[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [66]:
mat_slice = np.array(mat[:2,:2]) # Notice the np.array command to create a new array not just slicing
print ("\nSliced matrix")
print(mat_slice)



Sliced matrix
[[11 12]
 [21 22]]


In [67]:
print ("\nChange the sliced matrix")
mat_slice[0,0] = 1000
print (mat_slice)



Change the sliced matrix
[[1000   12]
 [  21   22]]


In [68]:
print("\nBut the original matrix? NO CHANGE this time:)")
print(mat)


But the original matrix? NO CHANGE this time:)
[[11 12 13]
 [21 22 23]
 [31 32 33]]


# Universal Functions

In [69]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)



1st Matrix of random single-digit numbers
----------------------------------------
 [[5 3 3]
 [7 7 7]
 [1 7 8]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[8 2 8]
 [1 5 9]
 [8 5 4]]


In [70]:
mat1*mat2

array([[40,  6, 24],
       [ 7, 35, 63],
       [ 8, 35, 32]])

In [71]:
#print("\nAddition\n------------------\n", mat1+mat2)
print("\nMultiplication\n------------------\n", mat1@mat2)



Multiplication
------------------
 [[ 67  40  79]
 [119  84 147]
 [ 79  77 103]]


In [72]:
print("\nDivision\n------------------\n", mat1/0)
#print("\nLineaer combination: 3*A - 2*B\n-----------------------------\n", 3*mat1-2*mat2)



Division
------------------
 [[inf inf inf]
 [inf inf inf]
 [inf inf inf]]


C:\Users\Suresh\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


In [74]:
print("\nAddition of a scalar (100)\n-------------------------\n", 100+mat1)



Addition of a scalar (100)
-------------------------
 [[105 103 103]
 [107 107 107]
 [101 107 108]]


In [75]:
print("\nExponentiation, matrix cubed here\n----------------------------------------\n", mat1**3)
print("\nExponentiation, sq-root using pow function\n-------------------------------------------\n",pow(mat1,3))


Exponentiation, matrix cubed here
----------------------------------------
 [[125  27  27]
 [343 343 343]
 [  1 343 512]]

Exponentiation, sq-root using pow function
-------------------------------------------
 [[125  27  27]
 [343 343 343]
 [  1 343 512]]


# Broadcasting

In [174]:
#NumPy operations are usually done on pairs of arrays on an element-by-element basis. 
#In the simplest case, the two arrays must have exactly the same shape.
#NumPy’s broadcasting rule relaxes this constraint when the arrays’ shapes meet certain constraints. 
#When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing 
#dimensions, and works its way forward. Two dimensions are compatible when
#they are equal, or one of them is 1

In [76]:
start = np.zeros((4,4))
start= start+100
start 

array([[100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.]])

In [77]:
# create a rank 1 ndarray with 3 values
add_rows = np.array([1, 0, 2,5])
print(add_rows)

[1 0 2 5]


In [78]:
y = start + add_rows  # add to each row of 'start' using broadcasting
print(y)

[[101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]]


In [79]:
# create an ndarray which is 4 x 1 to broadcast across columns
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T
print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [80]:
# add to each column of 'start' using broadcasting
y = start + add_cols 
print(y)

[[100. 100. 100. 100.]
 [101. 101. 101. 101.]
 [102. 102. 102. 102.]
 [103. 103. 103. 103.]]


In [81]:
# this will just broadcast in both dimensions
add_scalar = np.array([100])  
print(start+y)

[[200. 200. 200. 200.]
 [201. 201. 201. 201.]
 [202. 202. 202. 202.]
 [203. 203. 203. 203.]]


# Array Math

In [82]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n------------\n",mat2)



1st Matrix of random single-digit numbers

 [[5 1 6]
 [6 8 2]
 [9 3 8]]

2nd Matrix of random single-digit numbers
------------
 [[7 3 1]
 [5 9 1]
 [4 1 6]]


In [83]:
print("\nSq-root of 1st matrix using np\n------------------\n", np.sqrt(mat1))



Sq-root of 1st matrix using np
------------------
 [[2.23606798 1.         2.44948974]
 [2.44948974 2.82842712 1.41421356]
 [3.         1.73205081 2.82842712]]


In [84]:
print("\nExponential power of 1st matrix using np\n",'-'*50,"\n", np.exp(mat1))



Exponential power of 1st matrix using np
 -------------------------------------------------- 
 [[1.48413159e+02 2.71828183e+00 4.03428793e+02]
 [4.03428793e+02 2.98095799e+03 7.38905610e+00]
 [8.10308393e+03 2.00855369e+01 2.98095799e+03]]


In [85]:
print("\n10-base logarithm on 1st matrix using np\n",'-'*50,"\n", np.log10(mat1))
print(mat1)
print(mat2)


10-base logarithm on 1st matrix using np
 -------------------------------------------------- 
 [[0.69897    0.         0.77815125]
 [0.77815125 0.90308999 0.30103   ]
 [0.95424251 0.47712125 0.90308999]]
[[5 1 6]
 [6 8 2]
 [9 3 8]]
[[7 3 1]
 [5 9 1]
 [4 1 6]]


In [86]:
print("\nModulo reminder using np\n",'-'*50,"\n", np.fmod(mat1,mat2))
mat1%mat2


Modulo reminder using np
 -------------------------------------------------- 
 [[5 1 0]
 [1 8 0]
 [1 0 2]]


array([[5, 1, 0],
       [1, 8, 0],
       [1, 0, 2]], dtype=int32)

In [87]:
print("\nCombination of functions by shwoing exponetial decay of a sine wave\n",'-'*70)



Combination of functions by shwoing exponetial decay of a sine wave
 ----------------------------------------------------------------------


In [88]:
A = np.linspace(0,12*np.pi,1001)


In [89]:
A

array([ 0.        ,  0.03769911,  0.07539822, ..., 37.62371362,
       37.66141273, 37.69911184])